### PR TITLE
Implement missing quality of life features [3/3] 

### PR DESCRIPTION
**Pull request by Rush-er**
Change-Id: I19732ad94742db2041c4ddd27addae8e6b5bf5ed

### CODE REVIEW

**Comment by Rush-er** [comment]
Reflect new category schema

**Comment by Rush-er** [comment]
Fixed an error for the missing strings

**Comment by eldainosor** [comment]
> Fixed an error for the missing strings

These missing string commits are for things in settings, why not add those missing strings on settings instead?

**Comment by Rush-er** [comment]
> > Fixed an error for the missing strings
> 
> These missing string commits are for things in settings, why not add those missing strings on settings instead?

will fix this asap

**Pull request closed without merging**
